# Generated by Django 4.0.4 on 2022-05-16 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidentdb',
            fields=[
                ('incident_department', models.CharField(max_length=100)),
                ('incident_topic', models.CharField(max_length=100)),
                ('incident_description', models.TextField(verbose_name='incident_description')),
                ('incident_priority', models.CharField(max_length=50)),
                ('incident_status', models.CharField(max_length=20)),
                ('incident_ticket', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='incident_ticket')),
                ('incident_date', models.DateTimeField(verbose_name='incident_date')),
                ('incident_resolved_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Userdb',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('email', models.EmailField(blank=True, max_length=100, unique=True, verbose_name='email')),
                ('department', models.CharField(max_length=100, verbose_name='department')),
                ('role', models.CharField(max_length=100, verbose_name='role')),
                ('firstname', models.CharField(max_length=100, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=100, verbose_name='lastname')),
            ],
        ),
        migrations.CreateModel(
            name='StatusUpdatedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_status_update', models.TextField(verbose_name='incident_status_update')),
                ('update_date', models.DateTimeField()),
                ('incident_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RIT.incidentdb')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RIT.userdb')),
            ],
        ),
        migrations.AddField(
            model_name='incidentdb',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RIT.userdb'),
        ),
        migrations.CreateModel(
            name='Admindb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_topic', models.CharField(max_length=100)),
                ('incident_resolution', models.TextField(verbose_name='incident_resolution')),
                ('resolution_status', models.CharField(max_length=20)),
                ('report_date', models.DateTimeField(verbose_name='report_date')),
                ('resolved_date', models.DateTimeField(verbose_name='resolved_date')),
                ('ticket_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RIT.incidentdb')),
            ],
        ),
    ]
