# Generated by Django 4.0.4 on 2022-05-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentdb',
            name='incident_resolved_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
