# Generated by Django 4.0.4 on 2022-06-17 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RIT', '0003_alter_incidentdb_incident_resolved_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolutiondb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_topic', models.CharField(max_length=100)),
                ('incident_resolution', models.TextField(verbose_name='incident_resolution')),
                ('resolution_status', models.CharField(max_length=20)),
                ('report_date', models.DateTimeField(verbose_name='report_date')),
                ('resolved_date', models.DateTimeField(verbose_name='resolved_date')),
                ('ticket_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RIT.incidentdb')),
                ('user_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RIT.userdb')),
            ],
        ),
        migrations.DeleteModel(
            name='Admindb',
        ),
    ]
