# Generated by Django 4.0.4 on 2022-06-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RIT', '0004_resolutiondb_delete_admindb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusupdatedb',
            old_name='incident_topic',
            new_name='incident',
        ),
    ]
