# Generated by Django 4.0.4 on 2022-06-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RIT', '0005_rename_incident_topic_statusupdatedb_incident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusupdatedb',
            old_name='incident',
            new_name='incident_id',
        ),
    ]
