# Generated by Django 4.0.4 on 2022-06-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RIT', '0006_rename_incident_statusupdatedb_incident_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusupdatedb',
            old_name='incident_id',
            new_name='incident',
        ),
    ]
