# Generated by Django 4.0.4 on 2022-06-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIT', '0007_rename_incident_id_statusupdatedb_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentdb',
            name='incident_resolution',
            field=models.TextField(blank=True, null=True, verbose_name='incident_resolution'),
        ),
    ]
